- id: vzstorage_install
  role: [controller,compute]
  type: puppet
  requires: [post_deployment_end]
  required_for: [vzstorage_setup]
  parameters:
    puppet_manifest: puppet/manifests/vzstorage_install.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: vzstorage_setup
  role: [controller,compute]
  type: puppet
  requires: [vzstorage_install]
  required_for: [configure_cinder_backend,configure_glance_backend,configure_nova_backend]
  condition: "settings:vzstorage.use_exist_vzstorage.value == false"
  parameters:
    puppet_manifest: puppet/manifests/vzstorage_setup.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: vzstorage_authorize
  role: [controller,compute]
  type: puppet
  requires: [vzstorage_install]
  required_for: [configure_cinder_backend,configure_glance_backend,configure_nova_backend]
  condition: "settings:vzstorage.use_exist_vzstorage.value == true"
  parameters:
    puppet_manifest: puppet/manifests/vzstorage_authorize.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: configure_cinder_backend
  role: [cinder]
  type: puppet
  condition: "settings:vzstorage.use_vzstorage_as_cinder_backend.value == true"
  requires: [post_deployment_end,vzstorage_setup]
  parameters:
    puppet_manifest: puppet/manifests/configure_cinder_backend.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800