######################## ROLES #############################
- id: primary-vzstorage-mds
  type: group
  role: [primary-vzstorage-mds]
  tasks: [globals]
  parameters:
   strategy:
    type: one_by_one 

- id: vzstorage-mds
  type: group
  role: [vzstorage-mds]
  tasks: [globals]
  parameters:
   strategy:
    type: parallel

- id: vzstorage-csd
  type: group
  role: [vzstorage-csd]
  tasks: [globals]
  parameters:
   strategy:
    type: parallel

######################## MDS ########################
- id: configure_primary_mds
  role: [primary-vzstorage-mds]
  type: puppet
  requires: [post_deployment_begin]
  parameters:
    puppet_manifest: puppet/manifests/configure_primary_mds.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: configure_mds
  role: [vzstorage-mds]
  type: puppet
  requires: [configure_primary_mds]
  parameters:
    puppet_manifest: puppet/manifests/configure_mds.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

######################## CHUNK SERVER #####################
- id: mount_partitions
  role: [vzstorage-csd]
  type: puppet
  requires: [configure_primary_mds]
  parameters:
    puppet_manifest: puppet/manifests/mount_partitions.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: install_csd
  role: [vzstorage-csd]
  type: puppet
  requires: [mount_partitions]
  parameters:
    puppet_manifest: puppet/manifests/install_csd.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800
####################### CINDER BACKEND ##################
- id: configure_cinder_backend
  role: [cinder]
  type: puppet
  requires: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/configure_cinder_backend.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800
