######################## ROLES #############################
- id: vzstorage-master-mds
  type: group
  role: [vzstorage-master-mds]
  tasks: [globals]
  parameters:
   strategy:
    type: parallel

- id: vzstorage-slave-mds
  type: group
  role: [vzstorage-slave-mds]
  tasks: [globals]
  parameters:
   strategy:
    type: parallel

- id: vzstorage-csd
  type: group
  role: [vzstorage-csd]
  tasks: [globals]
  parameters:
   strategy:
    type: parallel

######################## MASTER MDS ########################
- id: configure_cluster_discovery
  role: [vzstorage-mds-master]
  type: puppet 
  requires: [post_deployment_begin]
  parameters:
    puppet_manifest: puppet/manifests/cluster_discovery.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: install_master_mds
  role: [vzstorage-mds-master]
  type: puppet
  requires: [post_deployment_begin, configure_cluster_discovery]
  parameters:
    puppet_manifest: puppet/manifests/install_master_mds.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800


######################## SLAVE MDS #########################
- id: configure_namespace
  role: [vzstorage-mds-slave]
  type: puppet
  requires: [install_master_mds]
  parameters:
    puppet_manifest: puppet/manifests/configure_namespace.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: install_slave_mds
  role: [vzstorage-mds-slave]
  type: puppet
  requires: [install_master_mds, configure_namespace]
  parameters:
    puppet_manifest: puppet/manifests/install_slave_mds.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

######################## CHUNK SERVER #####################
- id: mount_partitions
  role: [vzstorage-csd]
  type: puppet
  requires: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/mount_partitions.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: install_csd
  role: [vzstorage-csd]
  type: puppet
  requires: [mount_partitions]
  parameters:
    puppet_manifest: puppet/manifests/install_csd.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800
####################### CINDER BACKEND ##################
- id: configure_cinder_backend
  role: [cinder]
  type: puppet
  requires: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/configure_cinder_backend.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800