attributes:
  metadata:
  
  use_exist_vzstorage:
    type: "checkbox"
    weight: 30
    value: true
    label: "Checkbox label"
    description: "use exist vzstorage cluster"

  cluster_name:
    value: 'Set default value'
    label: 'Text field'
    description: 'Description for text field'
    weight: 25
    type: "text"

  cluster_password:
    value: 'Set default value'
    label: 'Text field'
    description: 'Description for text field'
    weight: 25
    type: "text"
    regex:
        source: '\S'
        error: "Error field cannot be empty"


  use_vzstorage_as_cinder_backend:
    type: "checkbox"
    weight: 30
    value: true
    label: "Checkbox label"
    description: "use vzstorage as cinder backend"


  #use_vzstorage_as_cinder_backend:
  #  type: "checkbox"
  #  weight: 30
  #  value: true
  #  label: "Checkbox label"
  #  description: "Checkbox description"

  use_vzstorage_as_nova_backend:
    type: "checkbox"
    weight: 30
    value: true
    label: "Checkbox label"
    description: "use vzstorage as nova backend"