attributes:
  metadata:
    group: 'storage'
  cluster_name:
    value: 'Set default value'
    label: 'cluster name'
    weight: 25
    type: "text"
    regex:
        source: '\S'
        error: "Error field cannot be empty"
  cluster_password:
    value: 'Set default value'
    label: 'cluster password'
    weight: 25
    type: "text"
    regex:
        source: '\S'
        error: "Error field cannot be empty"
