attributes:
  metadata:
    group: 'storage'

  use_exist_vzstorage:
    type: "checkbox"
    weight: 30
    value: true
    label: "Checkbox label"
    description: "use exist vzstorage cluster"

  cluster_name:
    value: 'Set default value'
    label: 'Text field'
    description: 'cluster name'
    weight: 25
    type: "text"
    regex:
        source: '\S'
        error: "Error field cannot be empty"

  cluster_password:
    value: 'Set default value'
    label: 'Text field'
    description: 'Description for text field'
    weight: 25
    type: "text"
    regex:
        source: '\S'
        error: "Error field cannot be empty"

  hdd_storage_devices:
    type: "text"
    value: ""
    label: ""
    description: "comma separated list of  hdd devices, example: /dev/sda,/dev/sdb."
    weight: 10
    regex:
      source: '^(/[a-zA-Z0-9:-_]+)+(,(/[a-zA-Z0-9:-_]+)+)*$'
      error: 'Incorrect list, write something like /dev/sda,/dev/sdb'

  ssd_storage_devices:
    type: "text"
    value: ""
    label: ""
    description: "comma separated list of  ssd devices, example: /dev/sda,/dev/sdb."
    weight: 10
    regex:
      source: '^(/[a-zA-Z0-9:-_]+)+(,(/[a-zA-Z0-9:-_]+)+)*$'
      error: 'Incorrect list, write something like /dev/sda,/dev/sdb'